export const mockUser = {
    id: 'mock-user-123',
    email: 'demo@inboxly.app',
    name: 'Demo User',
};

export const mockStats = {
    inboxHealthScore: 85,
    emailsProcessed: 1247,
    subscriptionsRemoved: 34,
    moneySaved: 127.50,
    noiseReduced: 67,
};

export const mockEmails = [
    {
        id: '1',
        from: 'Netflix <no-reply@netflix.com>',
        subject: 'Your monthly subscription renewal',
        snippet: 'Your subscription has been renewed for $15.99. Thank you for being a member!',
        body: 'Dear Customer, Your Netflix subscription has been renewed for $15.99...',
        category: 'Finance',
        noiseScore: 20,
        importanceScore: 80,
        isNewsletter: false,
        isPromo: false,
        hasUnsubscribe: true,
        receivedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        time: '2h ago',
    },
    {
        id: '2',
        from: 'TechCrunch Daily <newsletter@techcrunch.com>',
        subject: 'Today in Tech: AI Breakthroughs and Startup News',
        snippet: 'The latest news in technology, startups, and innovation from around the world...',
        body: 'Welcome to TechCrunch Daily! Here are today\'s top stories...',
        category: 'Newsletter',
        noiseScore: 60,
        importanceScore: 40,
        isNewsletter: true,
        isPromo: false,
        hasUnsubscribe: true,
        receivedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        time: '5h ago',
    },
    {
        id: '3',
        from: 'Amazon <ship-confirm@amazon.com>',
        subject: 'Your package has been delivered',
        snippet: 'Your order #123-4567890-1234567 has arrived at your doorstep',
        body: 'Good news! Your Amazon package has been delivered...',
        category: 'Shopping',
        noiseScore: 15,
        importanceScore: 90,
        isNewsletter: false,
        isPromo: false,
        hasUnsubscribe: false,
        receivedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        time: '1d ago',
    },
    {
        id: '4',
        from: 'LinkedIn <messages-noreply@linkedin.com>',
        subject: 'You have 3 new connection requests',
        snippet: 'Sarah Johnson, Mike Chen, and Emma Williams want to connect with you',
        body: 'You have new connection requests on LinkedIn...',
        category: 'Social',
        noiseScore: 45,
        importanceScore: 55,
        isNewsletter: false,
        isPromo: false,
        hasUnsubscribe: true,
        receivedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        time: '3h ago',
    },
    {
        id: '5',
        from: 'Udemy <no-reply@udemy.com>',
        subject: '🔥 Flash Sale: 80% off all courses',
        snippet: 'Limited time offer! Get any course for just $12.99. Sale ends tonight!',
        body: 'Don\'t miss out on our biggest sale of the year...',
        category: 'Promotions',
        noiseScore: 75,
        importanceScore: 25,
        isNewsletter: false,
        isPromo: true,
        hasUnsubscribe: true,
        receivedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        time: '6h ago',
    },
];

export const mockSubscriptions = [
    {
        id: '1',
        name: 'Netflix',
        email: 'no-reply@netflix.com',
        senderName: 'Netflix',
        amount: 15.99,
        currency: 'USD',
        billingCycle: 'monthly',
        nextBilling: '2025-12-15',
        emailCount: 12,
        frequency: 'Monthly',
        isBilling: true,
        isUnsubscribed: false,
    },
    {
        id: '2',
        name: 'Spotify Premium',
        email: 'noreply@spotify.com',
        senderName: 'Spotify',
        amount: 9.99,
        currency: 'USD',
        billingCycle: 'monthly',
        nextBilling: '2025-12-01',
        emailCount: 8,
        frequency: 'Monthly',
        isBilling: true,
        isUnsubscribed: false,
    },
    {
        id: '3',
        name: 'GitHub Pro',
        email: 'noreply@github.com',
        senderName: 'GitHub',
        amount: 4.00,
        currency: 'USD',
        billingCycle: 'monthly',
        nextBilling: '2025-12-10',
        emailCount: 24,
        frequency: 'Weekly',
        isBilling: true,
        isUnsubscribed: false,
    },
    {
        id: '4',
        name: 'TechCrunch Newsletter',
        email: 'newsletter@techcrunch.com',
        senderName: 'TechCrunch',
        amount: 0,
        currency: 'USD',
        billingCycle: null,
        nextBilling: null,
        emailCount: 156,
        frequency: 'Daily',
        isBilling: false,
        isUnsubscribed: false,
    },
    {
        id: '5',
        name: 'LinkedIn',
        email: 'messages-noreply@linkedin.com',
        senderName: 'LinkedIn',
        amount: 0,
        currency: 'USD',
        billingCycle: null,
        nextBilling: null,
        emailCount: 89,
        frequency: 'Daily',
        isBilling: false,
        isUnsubscribed: false,
    },
];

export const mockActivity = [
    {
        id: 1,
        action: 'Unsubscribed from',
        sender: 'Marketing Newsletter',
        time: '2 hours ago',
    },
    {
        id: 2,
        action: 'Analyzed',
        sender: '156 new emails',
        time: '5 hours ago',
    },
    {
        id: 3,
        action: 'Detected billing',
        sender: 'Netflix Subscription',
        amount: '$15.99',
        time: '1 day ago',
    },
    {
        id: 4,
        action: 'Archived',
        sender: '23 promotional emails',
        time: '2 days ago',
    },
];

export const mockBadges = [
    { id: 1, name: 'Inbox Ninja', unlocked: true },
    { id: 2, name: 'Signal Saver', unlocked: true },
    { id: 3, name: 'Zero Inbox Hero', unlocked: false },
    { id: 4, name: 'Subscription Samurai', unlocked: true },
];

export const mockCategories = [
    { id: 'all', label: 'All', count: 156 },
    { id: 'newsletter', label: 'Newsletters', count: 45 },
    { id: 'promotions', label: 'Promotions', count: 67 },
    { id: 'finance', label: 'Finance', count: 12 },
    { id: 'social', label: 'Social', count: 32 },
];
